---
- hosts: all
  gather_facts: false
  become: true
  become_method: su

  vars:
    ansible_user: '{{ user_name }}'
    ansible_password: '{{ user_current_pass }}'
    ansible_become_password: '{{ root_current_pass }}'

  tasks:
  - name: "Password Change user: {{ user_name }}"
    user:
      name: '{{ user_name }}'
      password: "{{ user_new_pass | password_hash('sha512','A512') }}"
    when: hostvars[inventory_hostname].service_type == find_service_type

  - name: "Password Change user: root"
    user:
      name: root
      password: "{{ root_new_pass | password_hash('sha512','A512') }}"
    when: hostvars[inventory_hostname].service_type == find_service_type