---
- hosts: all
  gather_facts: false
  become: true
  become_method: su

  vars:
    ansible_user: '{{ user_name }}'
    ansible_password: '{{ user_current_pass }}'
    ansible_become_password: '{{ root_current_pass }}'

  tasks:
  - name: Check Input variable [Hostname]
    set_fact:
      check_host: "{{ check_hosts.split(',') }}"
    run_once: true
    delegate_to: 127.0.0.1

  - when: "'all' in check_host"
    fail:
      msg: "[all] cannot be entered in Hostname vars"
    run_once: true
    delegate_to: 127.0.0.1


  tasks:
  - name: "Password Change user: {{ user_name }}"
    user:
      name: '{{ user_name }}'
      password: "{{ user_new_pass | password_hash('sha512','A512') }}"

  - name: "Password Change user: root"
    user:
      name: root
      password: "{{ root_new_pass | password_hash('sha512','A512') }}"